import type { ComfyApiNode, ComfyApiPrompt } from "./comfy-client.js";
import type { ImageJobReferenceInput } from "./image-job-repository.js";
import type {
  AnimaEngineSettings,
  ImageEditEngineSettings,
  KreaEngineSettings,
} from "./runtime-settings.js";

export const IMAGE_EDIT_MAX_REFERENCES = 4;
export const IMAGE_API_MAX_PIXELS = 4_000_000;
export const IMAGE_UI_TARGET_MAX_PIXELS = 2_000_000;
const KREA_REBALANCE_WEIGHTS =
  "1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.5,5.0,1.1,4.0,1.0";
const ANIMA_NEGATIVE_PROMPT =
  "worst quality, low quality, score_1, score_2, score_3, blurry, jpeg artifacts, sepia";
const REFERENCE_ROLE_LABELS: Record<ImageJobReferenceInput["role"], string> = {
  base: "base image",
  subject: "subject",
  style: "style",
  pose: "pose",
  background: "background",
  other: "additional reference",
};

function node(
  classType: string,
  inputs: Record<string, unknown>,
  title: string,
): ComfyApiNode {
  return { class_type: classType, inputs, _meta: { title } };
}

function loadImageName(file: string) {
  // ComfyUI uses the annotation to resolve files outside its input folder.
  // Removing it makes an image generated by H3 Studio impossible to reuse as
  // an Edit reference because LoadImage falls back to the input directory.
  return file.trim().replaceAll(String.fromCharCode(92), "/");
}

function cloneTemplate(template?: ComfyApiPrompt): ComfyApiPrompt {
  return template ? JSON.parse(JSON.stringify(template)) as ComfyApiPrompt : {};
}

export function assertImageDimensions(width: number, height: number) {
  if (
    !Number.isInteger(width) ||
    !Number.isInteger(height) ||
    width < 64 ||
    height < 64 ||
    width > 4096 ||
    height > 4096 ||
    width % 16 !== 0 ||
    height % 16 !== 0
  ) {
    throw new Error("Larghezza e altezza devono essere multipli di 16 fra 64 e 4096");
  }
  if (width * height > IMAGE_API_MAX_PIXELS) {
    throw new Error("La risoluzione immagine non può superare 4 megapixel");
  }
}

export function buildKreaGeneratePrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: KreaEngineSettings;
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // Rebuild the output path of the selected Krea blueprint with validated
  // runtime values while preserving any compatible extra nodes.
  for (const id of ["8", "9", "10", "11", "40", "41", "42", "43"]) {
    delete apiPrompt[id];
  }
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Krea image model",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "krea2", device: "default" },
      "Krea text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Krea VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: input.prompt, clip: ["2", 0] },
      "Image prompt",
    ),
    "5": node(
      "ConditioningKrea2Rebalance",
      {
        conditioning: ["4", 0],
        multiplier: 3,
        per_layer_weights: KREA_REBALANCE_WEIGHTS,
      },
      "Krea conditioning rebalance",
    ),
    "6": node(
      "ConditioningZeroOut",
      { conditioning: ["4", 0] },
      "Zero negative conditioning",
    ),
    "7": node(
      "EmptyLatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Image canvas",
    ),
  });
  let modelInput: [string, number] = ["1", 0];
  input.settings.loras.forEach((lora, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Krea LoRA ${index + 1}`,
    );
    modelInput = [id, 0];
  });
  apiPrompt["40"] = node(
    "KSampler",
    {
      model: modelInput,
      seed: input.seed,
      steps: input.settings.steps,
      cfg: 1,
      sampler_name: "er_sde",
      scheduler: "simple",
      positive: ["5", 0],
      negative: ["6", 0],
      latent_image: ["7", 0],
      denoise: 1,
    },
    "Krea image sampler",
  );
  apiPrompt["41"] = node(
    "VAEDecode",
    { samples: ["40", 0], vae: ["3", 0] },
    "Decode image",
  );
  apiPrompt["42"] = node(
    "ImageSharpenKJ",
    { image: ["41", 0], method: "rcas", "method.strength": 0.55 },
    "Image detail recovery",
  );
  apiPrompt["43"] = node(
    "SaveImage",
    { images: ["42", 0], filename_prefix: input.filenamePrefix },
    "Save generated image",
  );
  return apiPrompt;
}

export function buildAnimaGeneratePrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: AnimaEngineSettings;
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // The bundled Anima blueprint is authoritative and deliberately core-only.
  for (const id of Object.keys(apiPrompt)) delete apiPrompt[id];
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Anima image model",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "stable_diffusion", device: "default" },
      "Anima text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Anima VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: input.prompt, clip: ["2", 0] },
      "Anima prompt",
    ),
    "5": node(
      "CLIPTextEncode",
      { text: ANIMA_NEGATIVE_PROMPT, clip: ["2", 0] },
      "Anima negative prompt",
    ),
    "6": node(
      "EmptyLatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Anima canvas",
    ),
  });
  let modelInput: [string, number] = ["1", 0];
  input.settings.loras.forEach((lora, index) => {
    const id = String(20 + index);
    apiPrompt[id] = node(
      "LoraLoaderModelOnly",
      {
        model: modelInput,
        lora_name: lora.name,
        strength_model: lora.strength,
      },
      `Anima LoRA ${index + 1}`,
    );
    modelInput = [id, 0];
  });
  apiPrompt["40"] = node(
    "KSampler",
    {
      model: modelInput,
      seed: input.seed,
      steps: input.settings.steps,
      cfg: input.settings.cfg,
      sampler_name: "euler",
      scheduler: "simple",
      positive: ["4", 0],
      negative: ["5", 0],
      latent_image: ["6", 0],
      denoise: 1,
    },
    "Anima sampler",
  );
  apiPrompt["41"] = node(
    "VAEDecode",
    { samples: ["40", 0], vae: ["3", 0] },
    "Decode Anima image",
  );
  apiPrompt["42"] = node(
    "SaveImage",
    { images: ["41", 0], filename_prefix: input.filenamePrefix },
    "Save Anima image",
  );
  return apiPrompt;
}

export function buildFlux2KleinEditPrompt(input: {
  prompt: string;
  seed: number;
  width: number;
  height: number;
  filenamePrefix: string;
  settings: ImageEditEngineSettings;
  references: ImageJobReferenceInput[];
  template?: ComfyApiPrompt;
}): ComfyApiPrompt {
  assertImageDimensions(input.width, input.height);
  if (input.references.length < 1 || input.references.length > IMAGE_EDIT_MAX_REFERENCES) {
    throw new Error("Flux.2 Klein Edit richiede da 1 a 4 reference");
  }
  const referenceMap = input.references
    .map((reference, index) =>
      "Image " + (index + 1) + " = " +
      REFERENCE_ROLE_LABELS[reference.role] + " (" + reference.name + ")"
    )
    .join("; ");
  const editInstruction = input.prompt + "\n\nReference map: " + referenceMap + ".";
  const apiPrompt: ComfyApiPrompt = cloneTemplate(input.template);
  // Reference chains and optional accelerators are rebuilt for the requested
  // 1–4 inputs. Other nodes in a compatible selected blueprint are preserved.
  for (const id of ["10", "11", "60", "61", "62", "63"]) {
    delete apiPrompt[id];
  }
  for (let id = 20; id <= 39; id += 1) delete apiPrompt[String(id)];
  Object.assign(apiPrompt, {
    "1": node(
      "UNETLoader",
      { unet_name: input.settings.model, weight_dtype: "default" },
      "Flux.2 Klein 4B Distilled FP8",
    ),
    "2": node(
      "CLIPLoader",
      { clip_name: input.settings.encoder, type: "flux2", device: "default" },
      "Flux.2 Klein text encoder",
    ),
    "3": node("VAELoader", { vae_name: input.settings.vae }, "Flux.2 VAE"),
    "4": node(
      "CLIPTextEncode",
      { text: editInstruction, clip: ["2", 0] },
      "Edit instruction",
    ),
    "5": node(
      "ConditioningZeroOut",
      { conditioning: ["4", 0] },
      "Zero negative conditioning",
    ),
    "6": node(
      "EmptyFlux2LatentImage",
      { width: input.width, height: input.height, batch_size: 1 },
      "Flux.2 output canvas",
    ),
    "7": node("RandomNoise", { noise_seed: input.seed }, "Candidate noise"),
    "8": node("KSamplerSelect", { sampler_name: "euler" }, "Euler sampler"),
    "9": node(
      "Flux2Scheduler",
      { steps: input.settings.steps, width: input.width, height: input.height },
      "Flux.2 scheduler",
    ),
  });
  let guidedModel: [string, number] = ["1", 0];
  if (input.settings.attentionBackend !== "auto") {
    apiPrompt["11"] = node(
      "ModelAttentionBackend",
      {
        model: guidedModel,
        attention: input.settings.attentionBackend,
      },
      "Flux attention backend",
    );
    guidedModel = ["11", 0];
  }
  if (input.settings.kvCacheEnabled) {
    apiPrompt["10"] = node(
      "FluxKVCache",
      { model: guidedModel },
      "Flux reference KV cache",
    );
    guidedModel = ["10", 0];
  }

  let positive: [string, number] = ["4", 0];
  let negative: [string, number] = ["5", 0];
  const referenceMegapixels = 1;
  input.references.forEach((reference, index) => {
    const base = 20 + index * 5;
    const loadId = String(base);
    const scaleId = String(base + 1);
    const encodeId = String(base + 2);
    const positiveId = String(base + 3);
    const negativeId = String(base + 4);
    apiPrompt[loadId] = node(
      "LoadImage",
      { image: loadImageName(reference.file) },
      `Reference ${index + 1}: ${reference.role}`,
    );
    apiPrompt[scaleId] = node(
      "ImageScaleToTotalPixels",
      {
        image: [loadId, 0],
        upscale_method: "nearest-exact",
        megapixels: referenceMegapixels,
        resolution_steps: 1,
      },
      `Normalize reference ${index + 1}`,
    );
    apiPrompt[encodeId] = node(
      "VAEEncode",
      { pixels: [scaleId, 0], vae: ["3", 0] },
      `Encode reference ${index + 1}`,
    );
    apiPrompt[positiveId] = node(
      "ReferenceLatent",
      { conditioning: positive, latent: [encodeId, 0] },
      `Positive reference ${index + 1}`,
    );
    apiPrompt[negativeId] = node(
      "ReferenceLatent",
      { conditioning: negative, latent: [encodeId, 0] },
      `Negative reference ${index + 1}`,
    );
    positive = [positiveId, 0];
    negative = [negativeId, 0];
  });

  apiPrompt["60"] = node(
    "CFGGuider",
    {
      model: guidedModel,
      positive,
      negative,
      cfg: input.settings.cfg,
    },
    "Flux.2 guider",
  );
  apiPrompt["61"] = node(
    "SamplerCustomAdvanced",
    {
      noise: ["7", 0],
      guider: ["60", 0],
      sampler: ["8", 0],
      sigmas: ["9", 0],
      latent_image: ["6", 0],
    },
    "Flux.2 Klein edit sampler",
  );
  apiPrompt["62"] = node(
    "VAEDecode",
    { samples: ["61", 0], vae: ["3", 0] },
    "Decode edited image",
  );
  apiPrompt["63"] = node(
    "SaveImage",
    { images: ["62", 0], filename_prefix: input.filenamePrefix },
    "Save edited image",
  );
  return apiPrompt;
}
